#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

/* Core RFRAG configuration */
#define SICSLOWPAN_CONF_FRAG 1
#define SICSLOWPAN_CONF_RFRAG 1
#define SICSLOWPAN_CONF_RFRAG_FRAGMENT_SIZE 96
#define SICSLOWPAN_CONF_RFRAG_MAX_RETRIES 3
#define SICSLOWPAN_CONF_RFRAG_REASS_CONTEXTS 1
#define SICSLOWPAN_CONF_RFRAG_ARQ_TIMEOUT CLOCK_SECOND
#define SICSLOWPAN_CONF_RFRAG_MAX_ARQ_TIMEOUT (8 * CLOCK_SECOND)
#define UIP_CONF_BUFFER_SIZE 1800

/* Isolate 6LoWPAN recovery from MAC recovery. */
#define CSMA_CONF_MAX_FRAME_RETRIES 0

/* Logs */
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_INFO

/*
 * Select exactly one deterministic test:
 * 0 = no forced loss
 * 1 = drop first data fragment once
 * 2 = drop middle fragment seq 4 once
 * 3 = drop non-consecutive fragments seq {2,6,8} once
 * 4 = drop burst seq {4,5,6,7} once
 * 5 = drop first-fragment ACK once
 * 6 = drop partial bitmap ACK once after dropping seq 4
 * 7 = drop FULL bitmap ACK once
 * 8 = always drop first fragment until sender aborts
 * 9 = always drop middle fragment seq 4 until sender aborts
 */
#define RFRAG_TEST_CASE 6

#if RFRAG_TEST_CASE == 0

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 0

#elif RFRAG_TEST_CASE == 1

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x80000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 2

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x08000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 3

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x22800000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 4

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x0f000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 5

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x00000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 1
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 6

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x08000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 1
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 7

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x00000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 1
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 3
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 1
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 8

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x80000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 255
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#elif RFRAG_TEST_CASE == 9

#define SICSLOWPAN_CONF_RFRAG_TEST_ENABLE 1
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_NODE_ID 2
#define SICSLOWPAN_CONF_RFRAG_TEST_DATA_TARGET_TAG 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_BITMAP 0x08000000UL
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_DATA_MAX_PER_SEQ 255
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_NODE_ID 0xffff
#define SICSLOWPAN_CONF_RFRAG_TEST_ACK_TARGET_TAG 0xff
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_TYPE 0
#define SICSLOWPAN_CONF_RFRAG_TEST_DROP_ACK_COUNT 0
#define SICSLOWPAN_CONF_RFRAG_TEST_REPORT_MAC_NOACK 0

#else
#error Unknown RFRAG_TEST_CASE
#endif

#endif /* PROJECT_CONF_H_ */
